spring.application.name=booking-clinic
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/booking_clinic_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=12345678901234567890123456789012
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngnhatminh2k5@gmail.com
spring.mail.password=dpofbkirizjiagrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2
app.google.client-id=256663765383-frqgep8lipvok4l26r4ov0867g1ebt38.apps.googleusercontent.com

# Facebook OAuth2
app.facebook.app-id=YOUR_FACEBOOK_APP_ID_HERE
app.facebook.app-secret=YOUR_FACEBOOK_APP_SECRET_HERE
