/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#f4f9ff",
        "on-secondary-fixed-variant": "#004e60",
        "on-primary": "#ffffff",
        "tertiary-container": "#6a737b",
        "surface-bright": "#f8f9fa",
        "secondary-container": "#00ccf9",
        "secondary": "#00677f",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary-fixed": "#141d23",
        "on-primary-fixed-variant": "#003fa4",
        "surface-tint": "#0054d6",
        "on-secondary-fixed": "#001f28",
        "on-secondary-container": "#005266",
        "on-error-container": "#93000a",
        "primary-container": "#0066ff",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "tertiary": "#525b62",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed-dim": "#bfc8d0",
        "surface-container-high": "#e7e8e9",
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#001849",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "outline": "#727687",
        "primary": "#0050cb",
        "tertiary-fixed": "#dbe4ed",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#4cd6ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#3f484f",
        "on-surface": "#191c1d",
        "on-primary-container": "#f8f7ff",
        "error": "#ba1a1a",
        "inverse-primary": "#b3c5ff",
        "on-surface-variant": "#424656",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container": "#edeeef",
        "surface": "#f8f9fa",
        "primary-fixed": "#dae1ff",
        "error-container": "#ffdad6",
        "outline-variant": "#c2c6d8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "80px",
        "base": "8px",
        "xs": "4px",
        "gutter": "24px",
        "md": "24px",
        "lg": "48px",
        "sm": "12px",
        "margin": "32px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "h3": ["Manrope"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "h2": ["Manrope"],
        "h1": ["Manrope"],
        "body-lg": ["Inter"],
        "button": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h2": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "button": ["16px", {"lineHeight": "1", "fontWeight": "600"}]
      }
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
}
